# Below is the Github Action deploy code created as part of the CI Evaluate Github Actions project
# The action can be viewed and executed in the Actions tab of this repository
# The code deployment is currently managed by a Jenkins job and .jenkins/Jenkinsfile.
# This deploy config is the Github Actions version of that Jenkinsfile and is pointed at deploying develop code only

# name that will appear in the actions tab
name: Deploy Affiliations Code to AWS

# event that controls when the workflow will run
on: 
  # manual execution
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        default: 'develop'
        required: true
        type: choice
        options:
          - develop
          - main
          - qa
          - nana
          
# prevent multiple jobs running at the same time for jobs with the specified group
concurrency: 
  group: affil-${{ github.ref }}
  
env:
  branch: ${{ github.event.inputs.branch }}
  ref: ${{ github.ref }}
  build_env: ${{ github.event.inputs.branch }}

# as a first test, log the inputs and run
jobs:
  # name of the first job
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "branch: $branch"
          echo "ref: $ref"
          
          
      - name: Setup GitHub Script Action
        id: set-result
        uses: actions/github-script@v6.0.0
        with:
          # The script to run
          script: |
            if ('${{ env.branch }}' == 'develop' || '${{ env.branch }}' == 'qa') {
              return 'true'
            } else {
              return 'false'
            }
          result-encoding: string
          
      #- name: Match branch and environment
       # id: match-inputs
        # if: |
          # github.event.inputs.branch == 'develop' || github.event.inputs.branch == 'qa'
        # run: |
          # echo "::set-output name=match::true"
      
      - name: Check match result
        run: |
          echo "match result: ${{ steps.set-result.outputs.result }}"

  build:
      needs: [log-the-inputs]
#       if: github.event.inputs.branch == 'develop' || github.event.inputs.branch == 'qa'
      if: needs.log-the-inputs.outputs.set-result == 'true'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
