name: Testing Bash

on:
  workflow_dispatch:
    inputs:
      int:
        description: 'Integrations'
        required: true
        default: all
        type: choice
        options:
          - all
          - hr
      environment:
        description: 'Environment to run tests against'
        default: dev
        type: string
        required: true
      object:
        description: 'manual object entry'
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
       JSON_RESPONSE: ${{ inputs.object.Schedules }}
    steps:
      - run: |
          echo "Int: $INT"
          echo "Environment: $ENVIRONMENT"
          echo "
        env:
          INT: ${{ inputs.int }}
          ENVIRONMENT: ${{ inputs.environment }}
      - run: |
          echo '${{ env.JSON_RESPONSE }}' | jq '.'
  
