name: Testing Bash

on:
  workflow_dispatch:
    inputs:
      int:
        description: 'Integrations'
        required: true
        default: all
        type: choice
        options:
          - all
          - hr
      environment:
        description: 'Environment to run tests against'
        default: dev
        type: string
        required: true
      object:
        description: 'manual object entry'
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Int: $INT"
          echo "Environment: $ENVIRONMENT"
        env:
          INT: ${{ inputs.int }}
          ENVIRONMENT: ${{ inputs.environment }}
          JSON_RESPONSE: ${{ inputs.object }}
                
      - run: |
          echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' | jq '.'
  
