# This is a basic workflow to help you get started with Actions

name: Push Pull and Workflow Dispatch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      location:
        description: 'Location'
        required: true
        default: 'here'
        type: choice
        options:
        - here
        - there
        - everywhere

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Give me the input if it exists
        run: echo ${{ github.event.inputs.location }}

      # Runs a set of commands using the runners shell
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: Tell me what triggered this workflow run
        run: |
          echo "The branch or tag name that triggered the workflow run: $GITHUB_REF_NAME"
          echo "The name of the event that triggered the workflow: $GITHUB_EVENT_NAME"
